version: '2'
services:

    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - gateway

    mongo:
        image: mongo:3
        container_name: mongo
        command: mongod --smallfiles --bind_ip_all
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
        networks:
            - gateway

    status:
        image: shipyardsuite/status:develop
        container_name: status
        ports:
            - "3333:3333"
        depends_on:
            - redis
            - mongo
        environment:
            SERVICE_NAME: status
            SERVICE_PORT: 3333
        networks: 
            - gateway

    notfound:
        image: shipyardsuite/notfound:develop
        container_name: notfound
        ports:
            - "3003:3003"
        environment:
            SERVICE_PORT: 3003
        networks: 
            - gateway

    dashboard:
        image: shipyardsuite/dashboard:develop
        container_name: dashboard
        ports:
            - "3004:3004"
        depends_on:
            - redis
            - mongo
        environment:
            REDIS_URL: redis
            SERVICE_NAME: dashboard
            DATABASE_URL: ${DATABASE_URL}
            SERVICE_PORT: 3004
        networks: 
            - gateway

    auth:
        image: shipyardsuite/auth:develop
        container_name: auth
        ports:
            - "3002:3002"
        depends_on:
            - redis
            - mongo
        environment:
            REDIS_URL: redis
            SERVICE_NAME: auth
            DATABASE_URL: ${DATABASE_URL}
            SERVICE_PORT: 3002
        networks: 
            - gateway

    user:
        image: shipyardsuite/user:develop
        container_name: user
        ports:
            - "3005:3005"
        depends_on:
            - redis
            - mongo
        environment:
            REDIS_URL: redis
            SERVICE_NAME: user
            DATABASE_URL: ${DATABASE_URL}
            SERVICE_PORT: 3005
        networks: 
            - gateway

    homepage:
        build: ./
        container_name: homepage
        ports:
            - "${SERVICE_PORT}:${SERVICE_PORT}"
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run start:dev'
        depends_on: 
            - redis
            - mongo
        networks:
            - gateway
        environment:
            NODE_ENV: development
            REDIS_URL: redis
            SERVICE_NAME: ${SERVICE_NAME}
            SERVICE_PORT: ${SERVICE_PORT}
            DATABASE_URL: ${DATABASE_URL}

networks:
    gateway:
