version: '2'
services:

    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - gateway

    gateway:
        build: 
            context: ./gateway
            dockerfile: Dockerfile
        container_name: gateway
        ports:
            - "8080:8080"
            - "8443:8443"
            - "9876:9876"
        volumes:
            - ./gateway/system.config.yml:/usr/src/app/config/system.config.yml
            - ./gateway/gateway.config.yml:/usr/src/app/config/gateway.config.yml
        depends_on:
            - homepage
        networks:
            - gateway

    mongo:
        image: mongo:3
        container_name: mongo
        command: mongod --smallfiles --bind_ip_all
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
        networks:
            - gateway

    homepage:
        build: ./
        container_name: homepage
        ports:
            - "5000:5000"
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run start:dev'
        depends_on:
            - mongo 
        networks:
            - gateway
        environment:
            SERVICE_NAME: ${SERVICE_NAME}
            DATABASE_URL: ${DATABASE_URL}
            SERVICE_PORT: ${SERVICE_PORT}
            NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}

    template:
        image: shipyardsuite/microservice-template:latest
        container_name: template
        ports:
            - "3000:3000"
        environment: 
            SERVICE_NAME: template
            SERVICE_PORT: 3000
            DATABASE_URL: ${DATABASE_URL}
            NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}
        networks: 
            - gateway

networks:
    gateway:
