version: "3"

services:
    main:
        build: .
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run start:dev'
        container_name: main
        ports:
            - "3001:3001"
        networks:
            - all
        env_file:
            - .env
        environment:
            SERVICE_PORT: ${SERVICE_PORT}

    notfound:
        image: shipyardsuite/notfound:develop
        container_name: notfound
        ports:
            - "3003:3003"
        environment:
            SERVICE_PORT: 3003

networks:
    all:
