http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  template:
    host: localhost
    paths: [ '/template/*', '/template/api/*']
serviceEndpoints:
  template:
    url: 'http://template:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  template:
    apiEndpoints:
      - template
    policies:
      - proxy:
        - action:
            serviceEndpoint: template 
            changeOrigin: true
