http:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    template:
        host: localhost
        paths: [ '/template/*', '/template/api/*']
    api:
        host: '*'
        paths: '/ip'
    homepage:
        host: localhost
        paths: [ '/homepage/*', '/homepage/api/*']
serviceEndpoints:
    homepage:
        url: 'http://homepage:5000'
    template:
        url: 'http://template:3000'
    httpbin:
        url: 'https://httpbin.org'
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
pipelines:
    homepage:
        apiEndpoints:
            - homepage
        policies:
            - proxy:
                - action:
                    serviceEndpoint: homepage 
                    changeOrigin: true
    template:
        apiEndpoints:
            - template
        policies:
            - proxy:
                - action:
                    serviceEndpoint: template 
                    changeOrigin: true
    basic:
        apiEndpoints:
            - api
        policies:
            - proxy:
                - action:
                    serviceEndpoint: httpbin
                    changeOrigin: true
  